### ISSUE TITLE
1080p video download

### ISSUE THREAD

**Issue by Cybasaint** [ReneR97/skillshare-downloader#1]
Hi this downloads skillshare course in 720p, is there a way to get 1080p video? Thank you!

**Comment by Cybasaint** [comment]
Sorry, I dont know where to contact you, do you have a discord. The domestika app also allows users to download, is it possible for you to make a domestika downloader?

**Comment by ReneR97** [comment]
Never heard of domestika before, but i guess it could be possible. but its hard to say if they have some kind of api that you could access and how much effort that would be. they also dont offer a free trial or something like that so testing is extra difficult

**Comment by Cybasaint** [comment]
If you have discord, I could share my credentials and you can have a look! I also have a downloader of a kind made in golang, the creator of it said it worked 7 months ago and needed some adjustment for it to be functional now. Pls share your discord.

**Comment by ReneR97** [comment]
i mean sure, i could try it. 
Remling#6815
