### ISSUE TITLE
'ERR_UNHANDLED_REJECTION'  ... help

### ISSUE THREAD

**Issue by MOCKY2020** [ReneR97/skillshare-downloader#3]
C:\Users\Downloads\Compressed\skillshare-downloader-main>npm run start

> skillshare-scraper@1.0.0 start
> node index.js

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "false".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v18.16.0

**Comment by Shirshakkandel** [comment]
Yes same problem arise to me

**Comment by mhmdNoman** [comment]
@ReneR97 please can you fix this issue.

**Comment by ReneR97** [comment]
Hello,
i tried to replicate the error but was not able to. 

Can you send me the following info please: 

1. What course did you try to download
2. With Subtitles? If yes, what language
3. Does this happen with every course or just specific ones? 
4. Did you try to update the credentials? the phpsessid and skillshare_user_?

thanks in advance

**Comment by mhmdNoman** [comment]
I tried to download again after seeing your comment. it was downloading and having some other issue for which I'm gonna create another issue for that.

but a few hours later it's showing the same error.
tried on another machine with a different node version and OS.

1. I tried the course mentioned in the readme and also tried 2 different course that was downloading before.

**Comment by ReneR97** [comment]
This sounds like skillshare is limiting it somehow, will look into it.

**Comment by MOCKY2020** [comment]
> This sounds like skillshare is limiting it somehow, will look into it.

thanks.

**Comment by mhmdNoman** [comment]
The network is causing the problem. Videos don't load properly in the browser, but they work fine with a VPN and the script also works. My internet speed is decent, so the issue might be how the videos are being sent, or perhaps my ISP is involved. Oddly, this problem didn't happen before with the site.

**Comment by ReneR97** [comment]
Ok, tested it and found the problem. 
Skillshare uses couldflare for protection and maybe its new or maybe it was just never an issue before but its also used for the api. 
that means, if you download too much stuff in a short period of time, they will rate limit you, thats what the error is. 

so if you get the error, either wait a bit or use a vpn to circumwent it. getting around the rate limit isnt so easy, maybe with proxys but i dont know if thats even worth it

**Comment by ReneR97** [comment]
Ok, i think i found a middleground, i made some adjustments to how the async functions work in the script, which means it now downloads quite a lot slower but also more consistent. i tried downloading over 200 videos, and no rate limiting. 
so if you update the script, it should work now no problem. 

one thing to note, skillshare seems to have changed the way they load the subtitles, so they currently dont work anymore. will have to look into that when i have some time

**Comment by BitWizCoder-ol** [comment]
Yes, didn't face this problem before and it was temporary now the site seems to working fine. and tried with a VPN but the VPN is not stable for me. As you said I also don't think implementing the proxy will be a good idea for this project. and thanks for the middle ground :)
