### ISSUE TITLE
Download get stuck before finising.

### ISSUE THREAD

**Issue by mhmdNoman** [ReneR97/skillshare-downloader#4]
When trying to download longer courses, the download gets stuck before finishing a few videos. At first, I thought the issue was an expiring cookie, but it turns out the cookie is fine. The download doesn't finish due to other reasons, and there's no error message.

This happens with lengthy courses. I've tested with a few but couldn't complete the download. Here are some courses that have this problem:
- 1918569851
- 975237270
- 1088693386

Thanks for the script.

**Comment by ReneR97** [comment]
Thanks for the Bugreport. 
Seems like there was a bug with how the async downloading worked, so for example the first course you posted has 175 videos, and the script tried to download them all at once, which created errors and also had the potential to rate limit you. 
i updated the script, it now downloads a bit slower then before, but it should not have a problem with downloading lengthy courses anymore

**Comment by BitWizCoder-ol** [comment]
happy to contribute in any way I can. I would've contributed to the code if I could but the code is out of my reach atm. yes, the update is good How the videos are downloading is better than it was downloading before. tested with a few courses works as expected. thanks for the update.
